[font]
size = 13.0

[font.bold]
family = "Hack Nerd Font"

[font.bold_italic]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[general]

live_config_reload = true
import = ["~/.config/alacritty/colors/tokyonight_night.toml"]

